Revert lg profile friendly name
jellyfin/jellyfin-plugin-dlna pull request #77
Opened 2024-10-02 14:53 UTC by disgustipated

Add . back in to friendly name for LG TVs, caused rexeg to match unexpected friendly names of other devices Fixes https://github.com/jellyfin/jellyfin-plugin-dlna/issues/76

2024-10-02 15:06 UTC, Shadowghost commented
This PR has no changes

2024-10-02 15:10 UTC, disgustipated commented
Missed the commit, should be there now

2024-10-02 15:16 UTC, disgustipated commented
Good point, I'll see if i can test that

2024-10-04 12:24 UTC, FlashSystems commented
> I wonder if `Identification` conditions are `OR`ed together because otherwise it should only apply if the header also include `LG`, no? If yes, maybe they should be `AND`

I've taken a look at the code. The two identification parts are used at different locations within the code that seem to be completely unrelated. The PlayToManager calls GetProfile only passing the device identification (no headers here): https://github.com/jellyfin/jellyfin-plugin-dlna/blob/f7a4beaa5e12cfa40c38df49b97a23556a285773/src/Jellyfin.Plugin.Dlna/PlayTo/PlayToManager.cs#L211

The DlnaManager only uses the header fields and no device identification:
https://github.com/jellyfin/jellyfin-plugin-dlna/blob/f7a4beaa5e12cfa40c38df49b97a23556a285773/src/Jellyfin.Plugin.Dlna/DlnaManager.cs#L453

What makes everything really confusing that both methods are called `GetProfile` but do completely different things depending on if you pass a class that implements `IHeaderDictionary` or `DeviceIdentification`.

At first glance there is neither an AND nor an OR. They seem to be used for different things...

2024-10-05 09:42 UTC, andekande commented
You are right, there is no Regex needed. The simple contains check suffice.
However as its touched anyways one can consider to even add Manufacturer to make matches not to verbose:
    <FriendlyName>LG</FriendlyName>
    <Manufacturer>LG</Manufacturer>

Matches this strings of my TV:
FriendlyName: [LG] webOS TV OLED123456
Manufacturer: LG Electronics

2024-10-19 13:23 UTC, Bond-009 requested changes

2024-10-19 13:23 UTC, Bond-009 commented on src/Jellyfin.Plugin.Dlna/Profiles/Xml/LG Smart TV.xml
> +    <FriendlyName>LG.*</FriendlyName>
```suggestion
    <FriendlyName>LG</FriendlyName>
```

2024-10-19 16:35 UTC, Bond-009 approved these changes

2024-10-26 17:59 UTC, merged